dotnet: 3.1.402
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
script:
- dotnet restore
- dotnet build
solution: Andculture.Sitefinity.Testing.sln
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: ghRksdfEXH9E4MR4CyQSmg9ERPNHRx6jTXGbz92XERsl+rB2besJamDACJHf3tDLwL4jJ0czC2JXNv9tpMj5YnGo7GBlRY+vxc+403++mfdwaJ4tKu2/+SywyVuRtM1KLyMn/z3E+AGK7h581eIbKDblH/TRkcVzOImF9z351s2YFdfJhu26YKw/q9rm9ugz1K7qrzbrFTrU/rZuvHj0YNL4AKIJjJoASLzqlQrdxYFOGjoAcWz57SFQHb/iStobHVfDny3iOzxcX1dqQa8JENAPJZEwL/m9rJRuYEAWLTdmIY0aNyv1IkTt8Qy1No+Wa2F7/LrZCwVCz0DjYyG9BlWjO4JpnhKnTAPp6oXcFaXOspUecJPws73Zi4QmhqovFH9l0KkKaTDfw2GQhjYi1d1dOMOlx5huAPJfyOBO+w1KCnU8DesZP2QbqEyGxzc0A1mJKQkbXud07ifIluzyyYG/bqZZ70tdh4U8uTWc1mjokC3grGcS5tkujxRCZ2pnvZvzNbU1+DJBtHaJt/W0ugW0JE3Q1mS6YS0yvCCVZ9l0aX58CBlfwsik4DiaImF2RttpcHwkK54aIDN/fMOi4mN+m+whCUBz+KC2lnkIxDQ2Rx5p+t+USUclzrJ99h5UYyezZFR68YTyxCefEPY9HqI2WcBzUzlEbYC6awCuwLw=
