dotnet: 3.1.402
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
language: csharp
mono: none
script:
- dotnet restore
- dotnet build
solution: Andculture.Sitefinity.Testing.sln
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: L6/7FMfc/LqzDH2v04aDxH1EAf1O5x1IF8KmBkqJH9UqRDQ7lHDqqbS/ouZ4GBhoHj4zU6ZfSzc35xcX7I9zO0dn8/DEh7JXjlUkH4c4J9Nxi0pSOAHvOALMEsPcpI3j3akELw5+/xgRHgzAzZDtTuPkv6EVG0cLdrHmJqKcuqNn/8gEDRxZVpIiif8CTwvj/yFl5wm4l4TQ5BXOEm7Ha2Vwd0y1rbOKYIQ6KCzOIJA2UY3M4B08V0+xnB8fitfpQv0DxbFViZt+GiTHWdSvzTE073UdfWZXDJ6Xfjdmf/3Qn/3yWWYOXLjEvKfFuzdp81/q7cWQ1F8nl1iUWKIaCMWnh9uHZL3tnCzrtA95tRz7lpA1Ne3X4MJImvJknlofx3/kPrpEBvmnxZMZBn6Y1t2coVj39wjtcMNXu6IYATlu7BYOJufQFwc1+svIhDEzkgKFi5a8xsiqkEOwDntvtdQprPhK4zmKY9nSY9Vo26INVSme1D9Jsq2GffQjddZb9P3b96Ku746RSAOWtnVt6HwHNRxthDqHFdckJsYMPH+HiqDPk2gx9bLUtlBRFLhosQ1I9fOTrdZCTfi9KO9K8HpNgwUFW7bDAs327c5UROGO8QTCxiPypvBWlnLhbcaTZnQaAsStdjq0MUOZRZpoPQ3uWiTlB7sqcWoB8tln6aI=
